### ISSUE TITLE
Does not seem to work with WSL2 (Ubuntu)

### ISSUE THREAD

**Issue by Legion495** [Fabbi/autoshift#29]
Dunno how much relevance it has but I think someone should mention it.
I get the following trying to use this under WSL2.

Traceback (most recent call last):
  File "auto.py", line 218, in <module>
    main(args)
  File "auto.py", line 149, in main
    client = ShiftClient(args.user, args.pw)
  File "/home/legion495/autoshift/shift.py", line 110, in __init__
    if not self.__load_cookie():
  File "/home/legion495/autoshift/shift.py", line 165, in __load_cookie
    self.client.cookies.update(pickle.load(f))
EOFError: Ran out of input

It would be cool if it would run on the backed in Linux environment. Running under Windows works just fine :)

**Comment by Xebozone** [comment]
I too have this issue!

**Comment by HarryFry** [comment]
I got it working for me.

Example: `python3 ./auto.py --game bl3 --platform epic steam`

The thing is that it doesn't handle login errors. So if you type in your username or password incorrectly it just crashes and fails to tell you what you did wrong. The problem arises since it creates an empty cookie file when it fails. Then on subsequent runs, it tries to use that cookie file despite it not containing anything.

I got it working by deleting the `.cookies.save` file in the data folder and then double/triple checking that the user info I typed in was correct.

**Comment by Xebozone** [comment]
Even with the correct credentials, I couldn't get things working.
I had to put the username in "quotes" otherwise it would error at the "@" symbol in my username.
My password also had a symbol in it, which confused the script, I just changed my password to a long one without symbols, but the script still failed for me.

**Comment by Fabbi** [comment]
I am sorry for the late response. 

You should be fine with quoting Username and Password. I fixed the crash after a failed login attempt

**Comment by Xebozone** [comment]
Hi Fabbi! Thanks for fixing that!
Now, I noticed that it was getting a syntax error due to typing in a function.
I needed to install Python3 and pip3 too, then use update-alternatives to set the default to Python3 first
I also needed to re-install the dependencies after installing pip3
